SELECT Nome, Cognome, NomeS, CodT, Edizione, Posizione
FROM CICLISTA C, CLASSIFICA_INDIVIDUALE CI, SQUADRA S
WHERE C.CodC = CI.CodC AND C.CodS = S.CodS
AND C.CodC = 1 AND CI.CodT = 1
ORDER BY Edizione;
